package_update: true
package_upgrade: true

timezone: Europe/Berlin

manage_etc_hosts: true

packages:
  - docker.io
  - curl
  - git
  - snapd

users:
  - default
  - name: kamal
    groups:
      - sudo
      - docker
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_import_id:
      - gh:fugufisch
      - gh:poberherr
    uid: 1000

  - name: patrick
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:poberherr
    uid: 1001

  - name: max
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:fugufisch
    uid: 1002


write_files:
  - path: /etc/netplan/01-netplan.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            nameservers:
              addresses:
                - 1.1.1.1
                - 1.0.0.1
    permissions: "0600"
  - path: /home/kamal/docker-compose.yml
    content: |
      version: '3.8'

      services:
        clickhouse:
          image: clickhouse/clickhouse-server
          networks:
            - nenna-clickhouse-network
          ports:
            - "8123:8123"
          environment:
            - CLICKHOUSE_HOST=clickhouse-docker-server
            - CLICKHOUSE_PORT=8123
            - CLICKHOUSE_USERNAME=default
            - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

      networks:
        nenna-clickhouse-network:
          external: true
    permissions: "0644"
    owner: kamal:kamal

runcmd:
  - netplan apply
  - sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
  - echo "PermitRootLogin no" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - usermod -aG docker kamal
  - docker network create nenna-clickhouse-network
  - snap install btop
  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  - reboot
